# -*- coding: utf-8 -*-
"""pertemuan_strukturdata2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1n9ysNSWMCs-zGtTxRosIjedrA6-s19os
"""

#membuat linked list
#membuat node
class Node:
  def __init__(self,dataval=None):
    self.dataval = dataval
    self.nextval = None

n1 = Node("Januari")
n2 = Node("Februari")
n3 = Node("Maret")

print (n1.dataval)
print (n2.dataval)
print (n3.dataval)

#membuat class linked list
class LinkedList:
  def __init__(self):
    self.headval = None

Li = LinkedList()
Li.headval = n1

#link 1st node to 2nd node
Li.headval.nextval = n2

#link 2nd node to 3rd node
n2.nextval = n3

#menelusuri node dalam linked list
class Node:
  def __init__(self,dataval=None):
    self.dataval = dataval
    self.nextval = None

class LinkedList:
  def __init__(self):
    self.headval = None

  def listprint(self):
    printval = self.headval
    while printval is not None:
      print (printval.dataval)
      printval = printval.nextval

Li = LinkedList()
Li.headval = n1

#link 1st node to 2nd node
Li.headval.nextval = n2

#link 2nd node to 3rd node
n2.nextval = n3

Li.listprint()

#penyisipan node pada linked list
#penyisipan di awal

#membuat linked list
#membuat node
class Node:
  def __init__(self,dataval=None):
    self.dataval = dataval
    self.nextval = None

n1 = Node("Mercedes")
n2 = Node("BMW")
n3 = Node("Opel")

class LinkedList:
  def __init__(self):
    self.headval = None

  def listprint(self):
    printval = self.headval
    while printval is not None:
      print (printval.dataval)
      printval = printval.nextval

  def AtBegining(self,newdata):
    NewNode = Node(newdata)
    NewNode.nextval = self.headval
    self.headval = NewNode

Li = LinkedList()
Li.headval = n1

#link 1st node to 2nd node
Li.headval.nextval = n2

#link 2nd node to 3rd node
n2.nextval = n3

Li.AtBegining("Start")
Li.listprint()

#penyisipan di tengah
class Node:
  def __init__(self,dataval=None):
    self.dataval = dataval
    self.nextval = None

n1 = Node("Mercedes")
n2 = Node("BMW")

class LinkedList:
  def __init__(self):
    self.headval = None

  def listprint(self):
    printval = self.headval
    while printval is not None:
      print (printval.dataval)
      printval = printval.nextval

  def InBetween(self,middle_node,newdata):
    if middle_node is None:
      print("The mentioned node is absent")
      return
    NewNode = Node(newdata)
    NewNode.nextval = middle_node.nextval
    middle_node.nextval = NewNode

Li = LinkedList()
Li.headval = n1

Li.headval.nextval = n2

Li.InBetween(n1,"Mid_Jaguar")
Li.listprint()

#penyisipan di akhir
class Node:
  def __init__(self,dataval=None):
    self.dataval = dataval
    self.nextval = None

n1 = Node("Mercedes")
n2 = Node("BMW")

class LinkedList:
  def __init__(self):
    self.headval = None

  def listprint(self):
    printval = self.headval
    while printval is not None:
      print (printval.dataval)
      printval = printval.nextval

  def AddInEnd(self, newdata):
    NewNode = Node(newdata)
    if self.headval is None:
       self.headval = NewNode
       return
    Last = self.headval
    while (Last.nextval):
      Last = Last.nextval
    Last.nextval = NewNode


Li = LinkedList()
Li.headval = n1

Li.headval.nextval = n2

Li.AddInEnd("Last_Lancia")
Li.listprint()

#hapus node
class Node:
  def __init__(self,dataval=None):
    self.dataval = dataval
    self.nextval = None

class LinkedList:
  def __init__(self):
    self.headval = None

  def listprint(self):
    printval = self.headval
    while printval is not None:
      print (printval.dataval)
      printval = printval.nextval

  def AddBeginning(self,newdata):
    NewNode = Node(newdata)
    NewNode.nextval = self.headval
    self.headval = NewNode

  def RemoveNode(self, Removekey):
    HeadVal = self.headval

    if (HeadVal is not None):
      if (HeadVal.dataval == Removekey):
        self.headval = HeadVal.nextval
        HeadVal = None
        return
    while (HeadVal is not None):
      if HeadVal.dataval == Removekey:
        break
      prev = HeadVal
      HeadVal = HeadVal.nextval

    if (HeadVal == None):
      return
    prev.nextval = HeadVal.nextval
    HeadVal = None

Li = LinkedList()

Li.AddBeginning("Toyota")
Li.AddBeginning("Honda")
Li.AddBeginning("Suzuki")
print("Before removal")
Li.listprint()
print("=========================================================")
Li.RemoveNode("Honda")
print("After removal")
Li.listprint()

#hapus node di awal
class Node:
  def __init__(self,dataval=None):
    self.dataval = dataval
    self.nextval = None

class LinkedList:
  def __init__(self):
    self.headval = None

  def listprint(self):
    printval = self.headval
    while printval is not None:
      print (printval.dataval)
      printval = printval.nextval

  def AddBeginning(self,newdata):
    NewNode = Node(newdata)
    NewNode.nextval = self.headval
    self.headval = NewNode

  def RemoveBeginning(self):
    afterhead = self.headval
    self.headval = afterhead.nextval

Li = LinkedList()

Li.AddBeginning("Alfa Romeo")
Li.AddBeginning("Ferrari")
Li.AddBeginning("Lamborghini")
print("Before removal")
Li.listprint()
print("=========================================================")
Li.RemoveBeginning()
print("After removal of the first node")
Li.listprint()

#hapus node di akhir
class Node:
  def __init__(self,dataval=None):
    self.dataval = dataval
    self.nextval = None

class LinkedList:
  def __init__(self):
    self.headval = None

  def listprint(self):
    printval = self.headval
    while printval is not None:
      print (printval.dataval)
      printval = printval.nextval

  def AddInEnd(self, newdata):
    NewNode = Node(newdata)
    if self.headval is None:
       self.headval = NewNode
       return
    last = self.headval
    while (last.nextval):
      last = last.nextval
    last.nextval = NewNode

  def RemoveEnd(self):
    if self.headval is None:
      return
    if self.headval.nextval is None:
      self.headval = None
      return

    current = self.headval
    prev = None


    while current.nextval is not None:
      prev = current
      current = current.nextval


    if prev:
      prev.nextval = None

Li = LinkedList()

Li.AddInEnd("Ford")
Li.AddInEnd("Chevrolet")
Li.AddInEnd("Dodge")
print("Before removal")
Li.listprint()
print("=========================================================")
Li.RemoveEnd()
print("After removal of the last node")
Li.listprint()

class Node:
    def __init__(self, data):
        self.data = data
        self.next = None
        self.prev = None


class DoubleLinkedList:
    def __init__(self):
        self.head = None

    # Membuat 3 node awal
    def create_three_nodes(self):
        node1 = Node("Liberty Walk")
        node2 = Node("Brabus")
        node3 = Node("Gazoo Racing")

        # Menghubungkan node
        node1.next = node2
        node2.prev = node1

        node2.next = node3
        node3.prev = node2

        self.head = node1

    # Menampilkan isi list
    def display(self):
        current = self.head
        while current:
            print(current.data, end=" <-> ")
            current = current.next
        print("None")

    # Penyisipan setelah node tertentu (tengah)
    def insert_after(self, target, data):
        current = self.head

        # Mencari node target
        while current and current.data != target:
            current = current.next

        if current is None:
            print("Node not found!")
            return

        new_node = Node(data)

        # Mengatur pointer
        new_node.next = current.next
        new_node.prev = current

        if current.next:
            current.next.prev = new_node

        current.next = new_node

    # Hapus berdasarkan kata kunci
    def delete(self, key):
        current = self.head

        # Mencari node yang akan dihapus
        while current and current.data != key:
            current = current.next

        if current is None:
            print("Node not found!")
            return

        # Jika node pertama
        if current.prev is None:
            self.head = current.next
            if self.head:
                self.head.prev = None
        else:
            current.prev.next = current.next
            if current.next:
                current.next.prev = current.prev


# ===== Program Utama =====
dll = DoubleLinkedList()
dll.create_three_nodes()

print("Before Insertion :")
dll.display()



print("After Insertion:")
dll.insert_after("Brabus", "Mid")
dll.display()

dll.delete("Mid")

print("After Deletion:")
dll.display()

# circular linked list
class Node:
    def __init__(self, data):
        self.data = data
        self.next = None


class CircularLinkedList:
    def __init__(self):
        self.head = None

    def append(self, data):
        new_node = Node(data)

        if not self.head:
            self.head = new_node
            new_node.next = self.head
            return

        temp = self.head
        while temp.next != self.head:
            temp = temp.next

        temp.next = new_node
        new_node.next = self.head

    def delete_end(self):
        if not self.head:
            return

        # Jika hanya 1 node
        if self.head.next == self.head:
            self.head = None
            return

        temp = self.head
        prev = None

        while temp.next != self.head:
            prev = temp
            temp = temp.next

        prev.next = self.head

    def display(self):
        if not self.head:
            print("List empty")
            return

        temp = self.head
        while True:
            print(temp.data, end=" -> ")
            temp = temp.next
            if temp == self.head:
                break
        print("(back to head)")



# =======Program Utama=======

cll = CircularLinkedList()

# 3 node awal
cll.append('Jesko')
cll.append('Agera')
cll.append('Gemera')

print("Initial Data:")
cll.display()

# Tambah akhir
cll.append('CCX')
print("After adding the last :")
cll.display()

# Hapus akhir
cll.delete_end()
print("After deleting the last:")
cll.display()