# -*- coding: utf-8 -*-
"""pertemuan_strukturdata3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15GnxgXQGHvGDhF8oRXMkY18GYiXOXaTu
"""

#stack pada python
#stack dengan list
stack = []

stack.append('a')
stack.append('b')
stack.append('c')
stack.append('d')
stack.append('e')

print('initial stack')
print(stack)

print('\nelements popped from stack')
print(stack.pop())
print(stack.pop())
print(stack.pop())

print('\nstack after elements are popped')
print(stack)

#stack dengan collections.deque
from collections import deque
stack = deque()

stack.append('a')
stack.append('b')
stack.append('c')
stack.append('d')
stack.append('e')

print('initial stack')
print(stack)

print('\nelements popped from stack')
print(stack.pop())
print(stack.pop())
print(stack.pop())

print('\nstack after elements are popped')
print(stack)

#stack dengan queue.LifeQueue
from queue import LifoQueue
stack = LifoQueue(maxsize=5)

stack.put('a')
stack.put('b')
stack.put('c')
stack.put('d')
stack.put('e')

print("Full stack :", stack.full())
print("Stack size :", stack.qsize())

print('\nelements popped from stack')
print(stack.get())
print(stack.get())
print(stack.get())

print("\nEMPTY :", stack.empty())

class Node:
  def __init__(self, value):
    self.value = value
    self.next = None

class stack:

  def __init__(self):
    self.head = Node('head')
    self.size = 0

  def __str__(self):
    cur = self.head.next
    out = ""
    while cur:
      out += str (cur.value) + '->'
      cur = cur.next
    return out[:-2]

  def getSize(self):
    return self.size

  def isEmpty(self):
    return self.size == 0


  def peek(self):
    if self.isEmpty():
      raise Exception('Peeking from an empty stack')
    return self.head.next.value

  def push(self,value):
    node = Node(value)
    node.next = self.head.next
    self.head.next = node
    self.size += 1

  def pop(self):
    if self.isEmpty():
      raise Exception('popping from empty stack')
    remove = self.head.next
    self.head.next = self.head.next.next
    self.size -= 1
    return remove.value

if __name__ == "__main__":
  stack = stack()
  for i in range(1, 11):
    stack.push(i)
  print(f"stack: {stack}")

  for _ in range (1,6):
    remove = stack.pop()
    print(f'Pop: {remove}')
  print(f'stack: {stack}')