# -*- coding: utf-8 -*-
"""praktikum_strukturdata7tree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nt_vNp0OlsNumTKDLeqqIeFfjPXUhYmo
"""

#binary tree manual
class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)
root.left.right = Node(5)

def inorder(node):
    if node:
      inorder(node.left)
      print(node.data, end=' ')
      inorder(node.right)

print("hasil inorder tranversal dari binary tree:")
inorder(root)

#binary search tree
class Node:
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None

class BinarySearchTree:
    def __init__(self):
        self.root = None
    def insert(self, root, data):
        if self.root is None:
            return Node(data)
        if data < root.data:
            root.left = self.insert(root.left, data)
        else:
            root.right = self.insert(root.right, data)
        return root

bst = BinarySearchTree()
root = None
data_list = [5, 3, 7, 2, 4, 6, 8]
for value in data_list:
    root = bst.insert(root, value)

def inorder(node):
    if node:
      inorder(node.left)
      print(node.data, end=' ')
      inorder(node.right)

def preorder(node):
    if node:
      print(node.data, end=' ')
      preorder(node.left)
      preorder(node.right)

def postorder(node):
    if node:
      postorder(node.left)
      postorder(node.right)
      print(node.data, end=' ')

print("Inorder Transversal:")
inorder(root)
print("\nPreorder Transversal:")
preorder(root)
print("\nPostorder Transversal:")
postorder(root)

def search(node, key):
    if node is None or node.data == key:
        return node
    if key < node.data:
        return search(node.left, key)
    return search(node.right, key)

key = 60
result = search(root, key)
if result:
    print(f"Node dengan nilai {key} ditemukan.")
else:
    print(f"Node dengan nilai {key} tidak ditemukan.")

key = 25
result = search(root, key)
if result:
    print(f"Node dengan nilai {key} ditemukan.")
else:
    print(f"Node dengan nilai {key} tidak ditemukan.")

# Struktur Tree berdasarkan identitas saya
class Node:
  def __init__(self, data):
    self.data = data
    self.left = None
    self.right = None

# membuat root sesuai dengan ketentuan soal
root = Node(21)
root.left =  Node(8)
root.right = Node(24)
root.left.left = Node(8)
root.right.right = Node(2)

# menampilkan tree dengan inorder traversal
def inorder(node):
  if node:
    inorder(node.left)
    print(node.data, end=" ")
    inorder(node.right)

print("Hasil Inorder Traversal:")
inorder(root)

# class untuk merepresentasikan setiap node di dalam tree
class Node:
  def __init__(self, data):
    self.data = data
    self.left = None
    self.right = None

# class untuk struktur BST
class BinarySearchTree:
  def __init__(self):
    self.root = None

  # fungsi rekursif untuk menyisipkan (insert) data baru ke dalam BST
  def insert(self, root, data):
    if root is None:
      return Node(data)
    if data < root.data:
      root.left = self.insert(root.left, data)
    else:
      root.right = self.insert(root.right, data)
    return root

# fungsi rekursif untuk mencari (search) suatu nilai di dalam BST
def search(node, key):
  if node is None or node.data == key:
    return node
  if key < node.data:
    return search(node.left, key)
  return search(node.right, key)

bst = BinarySearchTree()
root = None

# daftar 7 angka berdasarkan ketentuan
data_list = [24, 8, 2, 77, 78, 44, 56]

# looping untuk memasukkan semua angka dari data_list ke dalam BST
for value in data_list:
  root = bst.insert(root, value)

# fungsi untuk menampilkan tree dengan inorder traversal
def inorder(node):
  if node:
    inorder(node.left)
    print(node.data, end=" ")
    inorder(node.right)

# fungsi untuk menampilkan tree dengan preorder traversal
def preorder(node):
  if node:
    print(node.data, end=" ")
    preorder(node.left)
    preorder(node.right)

# fungsi untuk menampilkan tree dengan postorder traversal
def postorder(node):
  if node:
    postorder(node.left)
    postorder(node.right)
    print(node.data, end=" ")

# menampilkan hasil setiap traversal
print("inorder Traversal:")
inorder(root)
print("\nPreorder Traversal:")
preorder(root)
print("\nPostorder Traversal:")
postorder(root)

print('\n==========================')

# fitur pencarian: Mencari nilai NPM
key_npm = 44
result = search(root, key_npm)
if result:
  print(f"{key_npm} ditemukan dalam tree.")
else:
  print(f"{key_npm} tidak ditemukan.")

# fitur pencarian: Mencari angka yang bebas dan tidak ada di dalam list
key = 38
result = search(root, key)
if result:
  print(f"{key} ditemukan dalam tree.")
else:
  print(f"{key} tidak ditemukan.")